### ISSUE TITLE
Some Questions regarding "change_methods" equivalent in near-api-js

### ISSUE THREAD

**Issue by Wabinab** [near-rails-guide/near_api#2]
Hi, I figured function call is `NearApi::Action.call(...)`, but how exactly do you make one? When I try tracking it down, it seems like there's some problem with access key: 

Particularly, 

```ruby
key = NearApi::Key.new
api.view_access_key(key)

=> {"jsonrpc"=>"2.0",
 "result"=>
  {"block_hash"=>"ARj9AriWfpfBWo5m7V6bob55Q57YUaE13SXhrkqXj3c",
   "block_height"=>86533146,
   "error"=>
    "access key ed25519:dKYi64UHPLfD4C7qUUWD3eWw1rv5GjLnTCzsNxo4W6Z does not exist while viewing",
   "logs"=>[]},
 "id"=>"dontcare"}
```

have an error. 

That is, I assume the public key is the "Hash" from the Explorer, but am I correct about that? If not, how do I get the key? 

And is there a login function to login with wallet for this? 

Thanks in advance.

**Comment by 2rba** [comment]
the function call is supposed to be signed with private key (keypair)
